Repository SMU-LIKELION-CENTRAL-HACKATHON-2TEAM/Team2-Back-End, pull requests merged in 2025-08, with the labels that each got.

#19 ✨ [Feat] 내가 작성한 리뷰 조회 API
  src/main/java/org/example/team2backend/domain/review/controller/ReviewController.java
  src/main/java/org/example/team2backend/domain/review/converter/ReviewConverter.java
  src/main/java/org/example/team2backend/domain/review/dto/response/ReviewResponseDTO.java
  src/main/java/org/example/team2backend/domain/review/service/query/ReviewQueryService.java
  src/main/java/org/example/team2backend/domain/route/repository/RoutePlaceRepository.java
  src/main/java/org/example/team2backend/domain/route/repository/RouteRepository.java
Labels: ✨feat

#22 :sparkles: feat: 이메일 중복검증 API
  src/main/java/org/example/team2backend/domain/member/controller/MemberController.java
  src/main/java/org/example/team2backend/domain/member/service/command/MemberCommandService.java
Labels: ✨feat

#23 ♻️ [Refactor] 사용자 API 리팩터링
  src/main/java/org/example/team2backend/domain/member/controller/MailController.java
  src/main/java/org/example/team2backend/domain/member/controller/MemberController.java
  src/main/java/org/example/team2backend/domain/member/converter/MemberConverter.java
  src/main/java/org/example/team2backend/domain/member/entity/EmailVerification.java
  src/main/java/org/example/team2backend/domain/member/entity/Member.java
  src/main/java/org/example/team2backend/domain/member/exception/MemberErrorCode.java
  src/main/java/org/example/team2backend/domain/member/repository/EmailVerificationRepository.java
  src/main/java/org/example/team2backend/domain/member/service/command/MailCommandService.java
  src/main/java/org/example/team2backend/domain/member/service/command/MemberCommandService.java
  src/main/java/org/example/team2backend/domain/member/service/query/MemberQueryService.java
  src/main/java/org/example/team2backend/domain/place/controller/PlaceController.java
  src/main/java/org/example/team2backend/domain/route/controller/RouteController.java
  src/main/java/org/example/team2backend/domain/route/entity/Route.java
  src/main/java/org/example/team2backend/domain/route/service/command/RouteCommandService.java
  src/main/java/org/example/team2backend/global/config/SecurityConfig.java
  src/main/java/org/example/team2backend/global/config/SwaggerConfig.java
Labels: ♻️refactor

#34 ✨ [Feat] 내가 쓴 리뷰 사진 응답 추가
  src/main/java/org/example/team2backend/domain/review/controller/ReviewController.java
  src/main/java/org/example/team2backend/domain/review/converter/ReviewConverter.java
  src/main/java/org/example/team2backend/domain/review/dto/request/ReviewRequestDTO.java
  src/main/java/org/example/team2backend/domain/review/dto/response/ReviewResponseDTO.java
  src/main/java/org/example/team2backend/domain/review/service/query/ReviewQueryService.java
Labels: ✨feat, ♻️refactor

#40 ♻️ [Refactor] cors 설정 수정
  src/main/java/org/example/team2backend/domain/member/entity/Member.java
  src/main/java/org/example/team2backend/global/config/CorsConfig.java
Labels: ♻️refactor

#42 ♻️ [Refactor] 인증 코드 발급 로직 수정 (Post -> Get)
  src/main/java/org/example/team2backend/domain/member/controller/MailController.java
Labels: ♻️refactor
